Initial Refactor to Better Modularize Processing, Execution, Optimization, and Configuration (#73)
* New features (#58)

* add to_df, from_df for data records

Help users easily use DataRecord (and the chosen plan), that means they can easily use their data to execute a plan, the data could be from some df.

* Fix some includes

* fix imports in pytest

fix imports in pytest

* fix imports for test

fix imports for test

* centralize hash functions into a helper lib

centralize hash functions into a helper lib

* Add as_df, from_df methods for DataRecord, so users can easily use their own data in the computations.

Add as_df, from_df methods for DataRecord, so users can easily use their own data in the computations.

Next step will be making df format more natural for the computation engines. DataRecord is just a special format of df, so it should be possible.

* New features (#57)

* add to_df, from_df for data records

Help users easily use DataRecord (and the chosen plan), that means they can easily use their data to execute a plan, the data could be from some df.

* fix imports in pytest

fix imports in pytest

* fix imports for test

fix imports for test

* centralize hash functions into a helper lib

centralize hash functions into a helper lib

* Add as_df, from_df methods for DataRecord, so users can easily use their own data in the computations.

Add as_df, from_df methods for DataRecord, so users can easily use their own data in the computations.

Next step will be making df format more natural for the computation engines. DataRecord is just a special format of df, so it should be possible.

* I think we may still want to finish early for LimitScans; will check w/Mike

* Dataset accept list, df as inputs.

# Change Description

### Datasources.py
1. Auto generate schema for MemorySource output_schema
2. MemorySource accepts more types

### Record.py
1. Move build_schema_from_df to Schema class
2. Make as_df() take para fields_in_schema

### schema.py
1. Add a new defaultSchema

### datamanager.py
1. Generate ID for memorySource instead of requiring dataset_id input from users
   - Future plan: Consider auto-generation for all data registry
   - Rationale: Users shouldn't need to manage data IDs manually

### datasource.py
1. Add get_datasource() method to centralize source retrieval in DataSource

### logical.py
1. Remove input_schema from BaseScan init() when not supported
   - LogicalOperator now accepts exactly 2 params for cleaner BaseScan

### sets.py
1. Dataset supports memory data as input

* resolve merge conflicts

* Update sets.py

* demo doesn't write to disk

* add pz update --name for pz config

add pz update --name for pz config

* The changes move away from a single class handling all responsibilities to a more modular design with separate strategies for optimization, execution, and processing. Key improvements include better configuration management through a dedicated Config class, clearer separation of concerns, and more maintainable strategy implementations. Future plans include improving Optimizer interface and the QueryProcessor interface. The refactoring maintains the existing clean interface while setting up a more scalable foundation for future development.

# Rationals
##Why this change:
### Previously
ExecutionEngine takes too many responsibilities for everything. In order to give one interface to users, we put everything into one class, which is not a good practice.
Different concepts are coupling together in ExecutionEngine, for example, execute_plan(), execute(), which is confusing. It’s easy to get messed up.
It’s not a good practice to new Execute() for running, as initiating an instance and running an instance are likely having different concerns, e.g. when testing, or we might want to pass instances to different places and run them in different modules.
### After this change
Separate core concepts to their dedicated models. The names can speak for themselves.
Put long params to Config which will be easier to maintain.
Each module is supposed to take care of one thing, and team will be easier to work together on the codebase.
Split out OptmizerStrategy, ExecutionStrategy, ProcessorStrategy QueryProcessor from ExecutionEngine, it will be easier to know where we need a new strategy, and don’t need to extend the huge class every time.
Interface is still clean. In the future, we’ll add “auto” for strategies, saying, the system can figure out the best strategies based on Dataset and params in Config, which will be easy to do in Factory.
### Important Notes
This is the first infra update, and I expect we can further refine the infrastructure so that PZ will be easier to scalable in the future.
I didn’t change any code inside functions to make this change easier to review, mostly just copy things around. If you see I deleted something, 99% because I moved it to another place.

##Next steps
After this change looks good to you, I’ll refactor all the demos.
I’ll see how to improve Optimizer interface.

QueryProcessor class can be improved further. Currently a new class inherits both ExecutionStrategy and ProcessorStrategy to make processor run correctly, I feel this can be improved.

Some strategies seem like not working, I’ll dig into some functionalities and further improve how we define and use strategies.

# Core Classes and Their Relationships
## QueryProcessor (Base Class)
Abstract base class that defines the query processing pipeline.

Dependencies:
- Optimizer - for plan optimization
- Dataset - for data source handling
- QueryProcessorConfig - for configuration, including policy

Implementation Includes
NoSentinelSequentialSingleThreadProcessor
NoSentinelPipelinedSinglelProcessor
NoSentinelPipelinedParallelProcessor
MABSentinelSequentialSingleThreadProcessor
MABSentinelPipelinedParallelProcessor
StreamingQueryProcessor
RandomSamplingSentinelSequentialSingleThreadProcessor
RandomSamplingSentinelPipelinedProcessor

## QueryProcessorFactory
Creates specific QueryProcessor implementations.

- Creates and configures different types of processors based on:
  - ProcessingStrategyType
  - ExecutionStrategyType
  - OptimizationStrategyType

## Optimizer
Create OptimizerStategy to implement optimize() for different OptimizerStategyTypes

## OptimizationStrategy (Abstract Base Class)

Defines interface for different optimization strategies.

Implementations include:
- GreedyStrategy
- ParetoStrategy
- SentinelStrategy
- ConfidenceIntervalStrategy
- NoOptimizationStrategy
- AutoOptimizationStrategy

* Add option to use plan.run() to execute the plan (Dataset).

Support plan.run() to executes the data pipeline, offering a streamlined way to build and process the data.

This design centralizes all operations around a single Plan (or Dataset) object, making it more intuitive to construct the pipeline and maintain focus on the data workflow.

* improve the readability of get_champion_model()

improve the readability of get_champion_model()

* leave TODO for gerardo

* add field types when possible for schemas derived from dataframes

* use  for record field access

* map both json str methods --> to_json_str; keep indentation consistent w/indent=2

* map all as_* verb fcns --> to_* for consistency

* lint check for List --> list, Tuple --> tuple; tried addressing TODO in code

* assert first physical operator is DataSourcePhysicalOp & use source_operator.get_datasource()

* remove typo

* add newline at end of file

* mostly lint changes

* rename optimize --> get_optimal_plan to clarify purpose a bit

* adding note about None for optimization strategy

---------

Co-authored-by: Michael Cafarella <michael.cafarella@gmail.com>
Co-authored-by: Matthew Russo <mdrusso@mit.edu>

* Support list, df when init Dataset() (#68)

* Support list, df when init Dataset()

Support list, df when init Dataset()

1. Auto generate dataset_id for memory source
2. create _tempRegistry for  memory data, it's temporary and won't be saved to disk. This is for providing unified interface for Datasource, we will need to revisit how to provide the best cache story in the system.
3. Mike mentioned Dataset init() can only take str/DataSource and move the logic to Datasource, I moved some logic to datamanager, and I still make init() takes list/str/df/datasource, since users need to create DataSource() when creating Dataset() if I don't do this, I'm in less favor of that. But if you still think that's better, I can update it. Or after I submit this change, Mike can update the code based on the current base.
---------

Co-authored-by: Matthew Russo <mdrusso@mit.edu>

* improve readability for source_op get_datasource() (#69)

* improve readability for source_op get_datasource()

improve readability for source_op get_datasource()

* add abstract methods for get_datasource, get_datasource_type

* ruff --fix check

---------

Co-authored-by: Matthew Russo <mdrusso@mit.edu>

* Refactor to a more modular design with separate strategies for optimizer, execution, processing. (#70)

* Refactor to a more modular design with separate strategies for optimization, execution, and processing. Key improvements include better configuration management through a dedicated Config class, clearer separation of concerns, and more maintainable strategy implementations.

# Rationals
##Why this change:
### Previously
ExecutionEngine takes too many responsibilities for everything. In order to give one interface to users, we put everything into one class, which is not a good practice.
Different concepts are coupling together in ExecutionEngine, for example, execute_plan(), execute(), which is confusing. It’s easy to get messed up.
It’s not a good practice to new Execute() for running, as initiating an instance and running an instance are likely having different concerns, e.g. when testing, or we might want to pass instances to different places and run them in different modules.
### After this change
Separate core concepts to their dedicated models. The names can speak for themselves.
Put long params to Config which will be easier to maintain.
Each module is supposed to take care of one thing, and team will be easier to work together on the codebase.
Split out OptmizerStrategy, ExecutionStrategy, ProcessorStrategy QueryProcessor from ExecutionEngine, it will be easier to know where we need a new strategy, and don’t need to extend the huge class every time.
Interface is still clean. In the future, we’ll add “auto” for strategies, saying, the system can figure out the best strategies based on Dataset and params in Config, which will be easy to do in Factory.
### Important Notes
This is the first infra update, and I expect we can further refine the infrastructure so that PZ will be easier to scalable in the future.
I didn’t change any code inside functions to make this change easier to review, mostly just copy things around. If you see I deleted something, 99% because I moved it to another place.

##Next steps
After this change looks good to you, I’ll refactor all the demos.

I’ll see how to improve Optimizer interface.

Explore how to add Human-in-the-loop for collecting users' feedback.

# Core Classes and Their Relationships
## QueryProcessor (Base Class)
Abstract base class that defines the query processing pipeline.

Dependencies:
- Optimizer - for plan optimization
- Dataset - for data source handling
- QueryProcessorConfig - for configuration, including policy

Implementation Includes
NoSentinelSequentialSingleThreadProcessor
NoSentinelPipelinedSinglelProcessor
NoSentinelPipelinedParallelProcessor
MABSentinelSequentialSingleThreadProcessor
MABSentinelPipelinedParallelProcessor
StreamingQueryProcessor
RandomSamplingSentinelSequentialSingleThreadProcessor
RandomSamplingSentinelPipelinedProcessor

## QueryProcessorFactory
Creates specific QueryProcessor implementations.

- Creates and configures different types of processors based on:
  - ProcessingStrategyType
  - ExecutionStrategyType
  - OptimizationStrategyType

## Optimizer
Create OptimizerStategy to implement optimize() for different OptimizerStategyTypes

## OptimizationStrategy (Abstract Base Class)

Defines interface for different optimization strategies.

Implementations include:
- GreedyStrategy
- ParetoStrategy
- SentinelStrategy
- ConfidenceIntervalStrategy
- NoOptimizationStrategy
- AutoOptimizationStrategy

* lint code

lint code

* rename optimize() to get_optimal_plan()

rename optimize() to get_optimal_plan()

* rename get_optimal_plan ---> get_optimal_plans

* fix optimizer initiation problem for processors

fix optimizer initiation problem for processors.

1. init optimizer every time in create_sentinel_plan and execute
2. update optimizerStrategyType for create_sentinel_plan.

* rename _execute_stategy to _execute_best_plan which is corresponding to _execute_confidence_interval

* rename to_jsonstr to to_json_str

* add note for NoOptimizationStrategy

* to break circle dependency

* make askem demo to run with the new format

* update name in comments

* small fix: remove a bad import

* update execute interface for bdf-suite.py

The code failed with the following error, but I think this is not from my change, so i'll still submit this update for now.

  File "/Users/chjun/Documents/GitHub/code/0122/palimpzest/demos/bdf-suite.py", line 229, in <module>
    for idx, (reference, plan, stats) in enumerate(iterable):
  File "/Users/chjun/Documents/GitHub/code/0122/palimpzest/src/palimpzest/query/processor/streaming_processor.py", line 84, in execute
    output_records = self.execute_opstream(self.plan, record)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chjun/Documents/GitHub/code/0122/palimpzest/src/palimpzest/query/processor/streaming_processor.py", line 147, in execute_opstream
    record_set = operator(r)
                 ^^^^^^^^^^^
  File "/Users/chjun/Documents/GitHub/code/0122/palimpzest/src/palimpzest/query/operators/convert.py", line 190, in __call__
    field_answers, generation_stats = self.convert(candidate=candidate, fields=fields_to_generate)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chjun/Documents/GitHub/code/0122/palimpzest/src/palimpzest/query/operators/convert.py", line 437, in convert
    field_answers, _, generation_stats = self.generator(candidate, fields, **gen_kwargs) # TODO: guarantee negative output from generator is None
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chjun/Documents/GitHub/code/0122/palimpzest/src/palimpzest/query/generators/generators.py", line 351, in __call__
    prompt = self._generate_user_prompt(candidate, fields, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chjun/Documents/GitHub/code/0122/palimpzest/src/palimpzest/query/generators/generators.py", line 194, in _generate_user_prompt
    field_lengths = [(field, len(value)) for field, value in context.items()]
                                                             ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'

* update bdf-usecase3 demo with the latest interface

* remove _should_stop_execution as we don't use it for now.

* update biofabric demo

* update fever-demo for the latest interface

* update demo-core

* Update image-demo.py

* execute_op_wrapper returns 3 values always

previously execute_op_wrapper() in different processes return 2 or 3 values, we unified this function and make it to returns 3 values.

* fix typo in caller functions

* add **kwargs in create_processor() to accept different params for different processors

1. add **kwargs in create_processor() to accept different params for different processors

2. readability: make functions classmethod so that calling name is shorter

* add **kwargs in run() to accept different params for different processors

* QueryProcessor should take dataset instead of datasource

* update optimizer-demo to use the latest interface

* update simple-demo.py to adopt the latest interface

* fix lint issue

* ruff --fix check

* fix a param error for fever demo

* more ruff --fix check

* Fix uint tests,  still 2 failing tests

There are still 2 tests failing:

tests/pytest/test_workloads.py::test_workload[enron-eval-tiny-enron-workload]

tests/pytest/test_optimizer.py::TestParetoOptimizer::test_pareto_optimization_strategy

* ruff fix

* fix test_optimizer unittest

* revert changes in conftest.py

* add one param in get_optimal_plans() to pass use_final_op_quality flag

Consider to use config structure if the params are getting larger.

---------

Co-authored-by: Matthew Russo <mdrusso@mit.edu>

* unit tests passing

* linting and fix sneaky data registration error in unit test

* look up dataset type in _tempRegistry as well

---------

Co-authored-by: Jun <130543538+chjuncn@users.noreply.github.com>
Co-authored-by: Michael Cafarella <michael.cafarella@gmail.com>
Co-authored-by: Matthew Russo <mdrusso@mit.edu>